language: c
compiler: gcc

before_install:
    - repo=$(pwd)
    - sudo apt-get update -qq

install:
    - sudo apt-get install -y libconfuse-dev
    - cd ..
    - wget http://sourceforge.net/projects/check/files/latest/download -O check_latest.tar.gz
    - tar xvfz check_latest.tar.gz
    - cd check-* && ./configure && make && sudo make install
    - cd ${repo}

script: ./configure --libdir=/lib/security --disable-dependency-tracking && make && make check

