language: c
compiler: gcc

notifications:
    email: false
    irc: "chat.freenode.net#pam_openssh_x509"

before_install:
    - sudo add-apt-repository "deb http://de.archive.ubuntu.com/ubuntu trusty main restricted universe multiverse"
    - sudo apt-get update -qq
    - sudo apt-get remove libssl-dev

install:
    - repo=$(pwd)
    - sudo apt-get install -y autotools-dev autoconf automake check libconfuse-dev libpam0g libpam0g-dev libtool
    - cd ..
    - wget --no-check-certificate https://www.openssl.org/source/openssl-1.0.2c.tar.gz
    - tar xvfz openssl-1.0.2c.tar.gz
    - cd openssl-1.0.2c
    - ./config --prefix=/usr shared && make && sudo make install
    - cd ${repo}

before_script:
    - ./autogen.sh
    - sudo mkdir -p /usr/local/etc/ssh/cacerts

script:
    - ./configure --libdir=/lib/security --disable-dependency-tracking
    - make
    - make check

