language: c
compiler: gcc

before_install:
    - repo=$(pwd)
    - sudo apt-get update -qq
    - sudo apt-get remove libssl-dev

install:
    - sudo ln -s /lib/x86_64-linux-gnu/libpam.so.0 lib/x86_64-linux-gnu/libpam.so
    - ld -lpam -verbose
    - sudo apt-get install -y libconfuse-dev
    - cd ..
    - wget http://sourceforge.net/projects/check/files/check/0.9.10/check-0.9.10.tar.gz/download -O check-0.9.10.tar.gz
    - tar xvfz check-0.9.10.tar.gz
    - cd check-0.9.10 && ./configure && make && sudo make install
    - cd ..
    - wget --no-check-certificate https://www.openssl.org/source/openssl-1.0.2a.tar.gz
    - tar xvfz openssl-1.0.2a.tar.gz
    - cd openssl-1.0.2a
    - ./config --prefix=/usr shared && make && sudo make install
    - cd ${repo}

script: ./configure --libdir=/lib/security --disable-dependency-tracking && make && make check

after_script: echo "hello world"
after_failure: cat config.log

