language: c
compiler: gcc

notifications:
    email: false
    irc: "chat.freenode.net#pam-openssh-x509"

before_install:
    - sudo add-apt-repository "deb http://de.archive.ubuntu.com/ubuntu trusty
        main restricted universe multiverse"
    - sudo apt-get update -qq

install:
    - sudo apt-get install -y autotools-dev autoconf automake check
        libconfuse-dev libpam0g libpam0g-dev libtool

before_script:
    - ./autogen.sh
    - sudo mkdir -p /usr/local/etc/ssh/cacerts

script:
    - ./configure --libdir=/lib/security --disable-dependency-tracking
    - make
    - make check

