language: c
compiler: gcc

before_install:
    - sudo add-apt-repository "deb http://de.archive.ubuntu.com/ubuntu trusty main restricted universe multiverse"
    - sudo apt-get update -qq
    - sudo apt-get remove libssl-dev

install:
    - repo=$(pwd)
    - sudo apt-get install -y autotools-dev autoconf automake check libconfuse-dev libpam0g libpam0g-dev libtool
    - cd ..
    - wget --no-check-certificate https://www.openssl.org/source/openssl-1.0.2a.tar.gz
    - tar xvfz openssl-1.0.2a.tar.gz
    - cd openssl-1.0.2a
    - ./config --prefix=/usr shared && make && sudo make install
    - cd ${repo}

before_script:
    - ./bootstrap
    - mkdir -p /usr/local/etc/ssh/cacerts

script:
    - ./configure --libdir=/lib/security --disable-dependency-tracking
    - make
    - make check

after_failure:
    - cd tests
    - ./pam_openssh_x509_check

